upd: run-migrations job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -176,7 +176,7 @@ jobs:
             --filters Name=instance-state-name,Values=running \
             --output text)
             curl -H "Content-Type: text/plain" -H \
-            "token: f5e67bb5-66c5-465a-b283-bfe16e1d4fbc" \
+            "token: ce-${CIRCLE_WORKFLOW_ID" \
             --request PUT --data "$var" https://api.memstash.io/values/backend-url
       - run:
           name: Install tar and gzip to persist to workdspace
@@ -253,25 +253,52 @@ jobs:
             echo "Success."
           # yes | ansible-playbook .circleci/ansible/configure-server.yml -i .circleci/ansible/inventory.txt
           # exit 1
-      
+      - persist_to_workspace:
+          root: ~/project/
+          paths:
+            - backend/.env
       # Here's where you will add some code to rollback on failure      
 
-  # run-migrations:
-  #   docker:
-  #     - image: circleci/node:13.8.0
-  #   steps:
-  #     - checkout
-  #     - run:
-  #         name: Run migrations
-  #         command: |
-  #           # Your code here
-  #           exit 1
-  #     - run:
-  #         name: Send migration results to memstash
-  #         command: |
-  #           # Your code here
-            # exit 1
-     # Here's where you will add some code to rollback on failure      
+  run-migrations:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Run migrations
+          command: |
+            touch migrations_result.txt
+            npm run migrations >> ~/project/backend/migrations_result.txt
+            echo 'DISPLAY CONTENTS'
+            echo '*****************'
+            cat migrations_result.txt
+          # Your code here
+          # exit 1
+      - run:
+          name: Send migration results to memstash
+          command: |
+            cd backend
+            pwd
+            cat ~/project/backend/migrations_result.txt
+
+            if grep -q "has been executed successfully." ~/project/backend/migrations_result.txt
+            then
+              curl -H "Content-Type: text/plain" -H "token: ce-${CIRCLE_WORKFLOW_ID}" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
+              echo migration_${CIRCLE_WORKFLOW_ID}
+              echo "SUCCESS = 1"
+            else
+              echo $(curl -H "Content-Type: text/plain" -H "token: ce-${CIRCLE_WORKFLOW_ID}" --request PUT --data "0" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID} | grep "No migrations")
+              echo "migration ID" migration_${CIRCLE_WORKFLOW_ID}
+              echo "FAIL = 0"
+            fi
+
+          # Your code here
+          # exit 1
+    #  Here's where you will add some code to rollback on failure      
 
 #   deploy-frontend:
 #     docker:
@@ -389,8 +416,8 @@ workflows:
               only: [test-feature-branch]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-#       - run-migrations:
-#           requires: [configure-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
 #       - deploy-frontend:
 #           requires: [run-migrations]
 #       - deploy-backend:
